import 'dart:ui';

import '../../data/model/call_log.dart';
import '../../data/model/chat.dart';

List<Chat> chats = [
  Chat(
    initials: "PC",
    name: "Pravin Chavan",
    time: "Today",
    messageType: 1,
    message: "Hi",
    isSent: true,
    isRead: true,
    unreadCnt: 5,
    isTimerOn: true,
    bgColor: Color(0xFF998800),
  ),
  Chat(
    initials: "AM",
    name: "Anita More",
    time: "Today",
    messageType: 3,
    message: "",
    isSent: false,
    isRead: false,
    unreadCnt: 3,
    isTimerOn: false,
    bgColor: Color(0xFF3366FF),
  ),
  Chat(
    initials: "RK",
    name: "Rahul Kulkarni",
    time: "10:45 AM",
    messageType: 3,
    message: "",
    isSent: true,
    isRead: false,
    unreadCnt: 0,
    isTimerOn: false,
    bgColor: Color(0xFF22AA99),
  ),
  Chat(
    initials: "SV",
    name: "Sneha Verma",
    time: "09:30 AM",
    messageType: 1,
    message: "Good morning",
    isSent: false,
    isRead: true,
    unreadCnt: 0,
    isTimerOn: false,
    bgColor: Color(0xFFFF8844),
  ),
  Chat(
    initials: "AP",
    name: "Amit Patil",
    time: "Yesterday",
    messageType: 2,
    message: "",
    isSent: false,
    isRead: false,
    unreadCnt: 4,
    isTimerOn: true,
    bgColor: Color(0xFF7755AA),
  ),
  Chat(
    initials: "NM",
    name: "Neha Mehta",
    time: "Yesterday",
    messageType: 1,
    message: "Thanks!",
    isSent: true,
    isRead: true,
    unreadCnt: 0,
    isTimerOn: false,
    bgColor: Color(0xFF44BB66),
  ),
  Chat(
    initials: "VS",
    name: "Vikas Sharma",
    time: "Mon",
    messageType: 3,
    message: "",
    isSent: false,
    isRead: false,
    unreadCnt: 6,
    isTimerOn: false,
    bgColor: Color(0xFFDD5566),
  ),
  Chat(
    initials: "KP",
    name: "Kiran Pawar",
    time: "Mon",
    messageType: 1,
    message: "Sent invoice",
    isSent: true,
    isRead: true,
    unreadCnt: 0,
    isTimerOn: false,
    bgColor: Color(0xFF339999),
  ),
  Chat(
    initials: "RJ",
    name: "Rohit Joshi",
    time: "Sun",
    messageType: 2,
    message: "",
    isSent: true,
    isRead: true,
    unreadCnt: 0,
    isTimerOn: false,
    bgColor: Color(0xFF6666FF),
  ),
  Chat(
    initials: "MS",
    name: "Meena Shah",
    time: "Sun",
    messageType: 1,
    message: "Please review",
    isSent: false,
    isRead: false,
    unreadCnt: 2,
    isTimerOn: true,
    bgColor: Color(0xFFAA8833),
  ),

  Chat(
    initials: "AK",
    name: "Ajay Kulkarni",
    time: "Sat",
    messageType: 3,
    message: "",
    isSent: true,
    isRead: true,
    unreadCnt: 0,
    isTimerOn: false,
    bgColor: Color(0xFF1188AA),
  ),
  Chat(
    initials: "PD",
    name: "Pooja Deshmukh",
    time: "Sat",
    messageType: 1,
    message: "On my way",
    isSent: false,
    isRead: false,
    unreadCnt: 1,
    isTimerOn: false,
    bgColor: Color(0xFFEE6677),
  ),
  Chat(
    initials: "SS",
    name: "Sahil Shah",
    time: "Fri",
    messageType: 2,
    message: "",
    isSent: true,
    isRead: true,
    unreadCnt: 0,
    isTimerOn: false,
    bgColor: Color(0xFF55AA55),
  ),
  Chat(
    initials: "HB",
    name: "Harsh Bhatt",
    time: "Fri",
    messageType: 1,
    message: "Check email",
    isSent: false,
    isRead: false,
    unreadCnt: 5,
    isTimerOn: true,
    bgColor: Color(0xFFAA4444),
  ),
  Chat(
    initials: "DG",
    name: "Deepak Gupta",
    time: "Thu",
    messageType: 3,
    message: "",
    isSent: true,
    isRead: true,
    unreadCnt: 0,
    isTimerOn: false,
    bgColor: Color(0xFF2288CC),
  ),
  Chat(
    initials: "TS",
    name: "Tanvi Shetty",
    time: "Thu",
    messageType: 1,
    message: "Can you help?",
    isSent: false,
    isRead: false,
    unreadCnt: 2,
    isTimerOn: false,
    bgColor: Color(0xFFCC9933),
  ),
  Chat(
    initials: "NB",
    name: "Nikhil Bansal",
    time: "Wed",
    messageType: 2,
    message: "",
    isSent: true,
    isRead: true,
    unreadCnt: 0,
    isTimerOn: false,
    bgColor: Color(0xFF33AA77),
  ),
  Chat(
    initials: "IG",
    name: "Isha Goyal",
    time: "Wed",
    messageType: 1,
    message: "😊",
    isSent: false,
    isRead: true,
    unreadCnt: 0,
    isTimerOn: false,
    bgColor: Color(0xFFDD88AA),
  ),
  Chat(
    initials: "MJ",
    name: "Manish Jain",
    time: "Tue",
    messageType: 3,
    message: "",
    isSent: true,
    isRead: false,
    unreadCnt: 0,
    isTimerOn: false,
    bgColor: Color(0xFF888888),
  ),
  Chat(
    initials: "RS",
    name: "Riya Singh",
    time: "Tue",
    messageType: 1,
    message: "Please confirm",
    isSent: false,
    isRead: false,
    unreadCnt: 3,
    isTimerOn: true,
    bgColor: Color(0xFFAA55FF),
  ),

  Chat(
    initials: "UP",
    name: "Uday Patil",
    time: "Mon",
    messageType: 2,
    message: "",
    isSent: true,
    isRead: true,
    unreadCnt: 0,
    isTimerOn: false,
    bgColor: Color(0xFF44AAFF),
  ),
  Chat(
    initials: "SK",
    name: "Shreya Kulkarni",
    time: "Mon",
    messageType: 1,
    message: "Thanks!",
    isSent: false,
    isRead: true,
    unreadCnt: 0,
    isTimerOn: false,
    bgColor: Color(0xFF77CC88),
  ),
  Chat(
    initials: "VP",
    name: "Vishal Pandey",
    time: "Sun",
    messageType: 3,
    message: "",
    isSent: true,
    isRead: false,
    unreadCnt: 0,
    isTimerOn: false,
    bgColor: Color(0xFFCC4444),
  ),
  Chat(
    initials: "AR",
    name: "Anjali Rao",
    time: "Sun",
    messageType: 1,
    message: "Sure 👍",
    isSent: false,
    isRead: true,
    unreadCnt: 0,
    isTimerOn: false,
    bgColor: Color(0xFF55BBBB),
  ),
  Chat(
    initials: "PK",
    name: "Pankaj Kumar",
    time: "Sat",
    messageType: 2,
    message: "",
    isSent: true,
    isRead: true,
    unreadCnt: 0,
    isTimerOn: false,
    bgColor: Color(0xFF999933),
  ),
  Chat(
    initials: "JD",
    name: "Jyoti Desai",
    time: "Sat",
    messageType: 1,
    message: "Will check",
    isSent: false,
    isRead: false,
    unreadCnt: 1,
    isTimerOn: false,
    bgColor: Color(0xFFBB7766),
  ),
  Chat(
    initials: "RM",
    name: "Rakesh Mishra",
    time: "Fri",
    messageType: 3,
    message: "",
    isSent: true,
    isRead: true,
    unreadCnt: 0,
    isTimerOn: false,
    bgColor: Color(0xFF66AA99),
  ),
  Chat(
    initials: "SP",
    name: "Sonali Patil",
    time: "Fri",
    messageType: 1,
    message: "Any update?",
    isSent: false,
    isRead: false,
    unreadCnt: 2,
    isTimerOn: true,
    bgColor: Color(0xFFDD6655),
  ),
  Chat(
    initials: "KK",
    name: "Kunal Kapoor",
    time: "Thu",
    messageType: 2,
    message: "",
    isSent: true,
    isRead: true,
    unreadCnt: 0,
    isTimerOn: false,
    bgColor: Color(0xFF5577AA),
  ),
];

List<Chat> channels = [
  Chat(
    initials: "FL",
    name: "Flutter Devs",
    time: "Today",
    messageType: 1,
    message: "Hi",
    isSent: true,
    isRead: true,
    unreadCnt: 5,
    isTimerOn: true,
    bgColor: Color(0xFF998800),
  ),
  Chat(
    initials: "AN",
    name: "Announcements",
    time: "Today",
    messageType: 2,
    message: "",
    isSent: false,
    isRead: false,
    unreadCnt: 3,
    isTimerOn: false,
    bgColor: Color(0xFF3366FF),
  ),
  Chat(
    initials: "GM",
    name: "General Chat",
    time: "10:45 AM",
    messageType: 1,
    message: "Good morning",
    isSent: false,
    isRead: true,
    unreadCnt: 0,
    isTimerOn: false,
    bgColor: Color(0xFFFF8844),
  ),
  Chat(
    initials: "HR",
    name: "HR Updates",
    time: "Yesterday",
    messageType: 3,
    message: "",
    isSent: false,
    isRead: false,
    unreadCnt: 4,
    isTimerOn: true,
    bgColor: Color(0xFF7755AA),
  ),
  Chat(
    initials: "BE",
    name: "Backend Team",
    time: "Mon",
    messageType: 2,
    message: "",
    isSent: false,
    isRead: false,
    unreadCnt: 6,
    isTimerOn: false,
    bgColor: Color(0xFFDD5566),
  ),
  Chat(
    initials: "UI",
    name: "UI / UX",
    time: "Mon",
    messageType: 1,
    message: "Please review",
    isSent: true,
    isRead: true,
    unreadCnt: 0,
    isTimerOn: false,
    bgColor: Color(0xFF339999),
  ),
  Chat(
    initials: "QA",
    name: "QA Testing",
    time: "Sun",
    messageType: 2,
    message: "",
    isSent: true,
    isRead: true,
    unreadCnt: 0,
    isTimerOn: false,
    bgColor: Color(0xFF6666FF),
  ),
  Chat(
    initials: "DV",
    name: "DevOps",
    time: "Sun",
    messageType: 3,
    message: "",
    isSent: true,
    isRead: false,
    unreadCnt: 0,
    isTimerOn: false,
    bgColor: Color(0xFF22AA99),
  ),
  Chat(
    initials: "PM",
    name: "Product Team",
    time: "Sat",
    messageType: 1,
    message: "Sprint planning",
    isSent: false,
    isRead: false,
    unreadCnt: 2,
    isTimerOn: true,
    bgColor: Color(0xFFAA8833),
  ),
  Chat(
    initials: "FN",
    name: "Finance",
    time: "Sat",
    messageType: 2,
    message: "",
    isSent: true,
    isRead: true,
    unreadCnt: 0,
    isTimerOn: false,
    bgColor: Color(0xFF44BB66),
  ),
  Chat(
    initials: "MK",
    name: "Marketing",
    time: "Fri",
    messageType: 1,
    message: "Campaign live",
    isSent: false,
    isRead: true,
    unreadCnt: 0,
    isTimerOn: false,
    bgColor: Color(0xFFCC9933),
  ),
  Chat(
    initials: "IT",
    name: "IT Support",
    time: "Fri",
    messageType: 3,
    message: "",
    isSent: false,
    isRead: false,
    unreadCnt: 1,
    isTimerOn: false,
    bgColor: Color(0xFFAA4444),
  ),
];

List<CallLog> callLogs = [
  CallLog(
    initials: "PC",
    name: "Pravin Chavan",
    callTime: "Today, 10:30 AM",
    callType: 1,
    callMode: "V",
    bgColor: Color(0xFF998800),
  ),
  CallLog(
    initials: "AM",
    name: "Anita More",
    callTime: "Today, 09:15 AM",
    callType: 2,
    callMode: "A",
    bgColor: Color(0xFF3366FF),
  ),
  CallLog(
    initials: "RK",
    name: "Rahul Kulkarni",
    callTime: "Yesterday, 06:45 PM",
    callType: 3,
    callMode: "V",
    bgColor: Color(0xFF22AA99),
  ),
  CallLog(
    initials: "SV",
    name: "Sneha Verma",
    callTime: "Yesterday, 02:10 PM",
    callType: 4,
    callMode: "A",
    bgColor: Color(0xFFFF8844),
  ),
  CallLog(
    initials: "AP",
    name: "Amit Patil",
    callTime: "29 January, 04:05 PM",
    callType: 1,
    callMode: "V",
    bgColor: Color(0xFF7755AA),
  ),
  CallLog(
    initials: "NM",
    name: "Neha Mehta",
    callTime: "29 January, 11:50 AM",
    callType: 2,
    callMode: "A",
    bgColor: Color(0xFF44BB66),
  ),
  CallLog(
    initials: "VS",
    name: "Vikas Sharma",
    callTime: "28 January, 01:20 PM",
    callType: 3,
    callMode: "V",
    bgColor: Color(0xFFDD5566),
  ),
  CallLog(
    initials: "KP",
    name: "Kiran Pawar",
    callTime: "28 January, 10:40 AM",
    callType: 4,
    callMode: "A",
    bgColor: Color(0xFF339999),
  ),
  CallLog(
    initials: "RJ",
    name: "Rohit Joshi",
    callTime: "27 January, 07:30 PM",
    callType: 1,
    callMode: "V",
    bgColor: Color(0xFF6666FF),
  ),
  CallLog(
    initials: "MS",
    name: "Meena Shah",
    callTime: "27 January, 09:05 AM",
    callType: 2,
    callMode: "A",
    bgColor: Color(0xFFAA8833),
  ),

  CallLog(
    initials: "AK",
    name: "Ajay Kulkarni",
    callTime: "26 January, 03:45 PM",
    callType: 3,
    callMode: "V",
    bgColor: Color(0xFF1188AA),
  ),
  CallLog(
    initials: "PD",
    name: "Pooja Deshmukh",
    callTime: "26 January, 12:10 PM",
    callType: 4,
    callMode: "A",
    bgColor: Color(0xFFEE6677),
  ),
  CallLog(
    initials: "SS",
    name: "Sahil Shah",
    callTime: "25 January, 05:00 PM",
    callType: 1,
    callMode: "V",
    bgColor: Color(0xFF55AA55),
  ),
  CallLog(
    initials: "HB",
    name: "Harsh Bhatt",
    callTime: "25 January, 02:20 PM",
    callType: 2,
    callMode: "A",
    bgColor: Color(0xFFAA4444),
  ),
  CallLog(
    initials: "DG",
    name: "Deepak Gupta",
    callTime: "24 January, 04:15 PM",
    callType: 3,
    callMode: "V",
    bgColor: Color(0xFF2288CC),
  ),
  CallLog(
    initials: "TS",
    name: "Tanvi Shetty",
    callTime: "24 January, 11:50 AM",
    callType: 4,
    callMode: "A",
    bgColor: Color(0xFFCC9933),
  ),
  CallLog(
    initials: "NB",
    name: "Nikhil Bansal",
    callTime: "23 January, 01:30 PM",
    callType: 1,
    callMode: "V",
    bgColor: Color(0xFF33AA77),
  ),
  CallLog(
    initials: "IG",
    name: "Isha Goyal",
    callTime: "23 January, 09:45 AM",
    callType: 2,
    callMode: "A",
    bgColor: Color(0xFFDD88AA),
  ),
  CallLog(
    initials: "MJ",
    name: "Manish Jain",
    callTime: "22 January, 06:20 PM",
    callType: 3,
    callMode: "V",
    bgColor: Color(0xFF888888),
  ),
  CallLog(
    initials: "RS",
    name: "Riya Singh",
    callTime: "22 January, 10:15 AM",
    callType: 4,
    callMode: "A",
    bgColor: Color(0xFFAA55FF),
  ),

  CallLog(
    initials: "UP",
    name: "Uday Patil",
    callTime: "21 January, 03:30 PM",
    callType: 1,
    callMode: "V",
    bgColor: Color(0xFF44AAFF),
  ),
  CallLog(
    initials: "SK",
    name: "Shreya Kulkarni",
    callTime: "21 January, 11:50 AM",
    callType: 2,
    callMode: "A",
    bgColor: Color(0xFF77CC88),
  ),
  CallLog(
    initials: "VP",
    name: "Vishal Pandey",
    callTime: "20 January, 05:05 PM",
    callType: 3,
    callMode: "V",
    bgColor: Color(0xFFCC4444),
  ),
  CallLog(
    initials: "AR",
    name: "Anjali Rao",
    callTime: "20 January, 01:40 PM",
    callType: 4,
    callMode: "A",
    bgColor: Color(0xFF55BBBB),
  ),
  CallLog(
    initials: "PK",
    name: "Pankaj Kumar",
    callTime: "19 January, 04:25 PM",
    callType: 1,
    callMode: "V",
    bgColor: Color(0xFF999933),
  ),
  CallLog(
    initials: "JD",
    name: "Jyoti Desai",
    callTime: "19 January, 12:10 PM",
    callType: 2,
    callMode: "A",
    bgColor: Color(0xFFBB7766),
  ),
  CallLog(
    initials: "RM",
    name: "Rakesh Mishra",
    callTime: "18 January, 03:50 PM",
    callType: 3,
    callMode: "V",
    bgColor: Color(0xFF66AA99),
  ),
  CallLog(
    initials: "SP",
    name: "Sonali Patil",
    callTime: "18 January, 10:30 AM",
    callType: 4,
    callMode: "A",
    bgColor: Color(0xFFDD6655),
  ),
  CallLog(
    initials: "KK",
    name: "Kunal Kapoor",
    callTime: "17 January, 02:20 PM",
    callType: 1,
    callMode: "V",
    bgColor: Color(0xFF5577AA),
  ),
  CallLog(
    initials: "TR",
    name: "Tanya Rao",
    callTime: "17 January, 09:10 AM",
    callType: 2,
    callMode: "A",
    bgColor: Color(0xFF44AA77),
  ),
];
