// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtq9WMf2kUyz6WKKbhO0KzptcEPumOwIE',
    appId: '1:781177281533:web:9c3ef2ddbcb5c842841794',
    messagingSenderId: '781177281533',
    projectId: 'whatsapp-clone-e948a',
    authDomain: 'whatsapp-clone-e948a.firebaseapp.com',
    storageBucket: 'whatsapp-clone-e948a.firebasestorage.app',
    measurementId: 'G-WTK9V6XR3V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdnOrkYMGOkyNcrALARYWvyrR54hebGLQ',
    appId: '1:781177281533:android:11e85d1ead153599841794',
    messagingSenderId: '781177281533',
    projectId: 'whatsapp-clone-e948a',
    storageBucket: 'whatsapp-clone-e948a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCecXgY1qLEpcjcuZEzer4E1VPM1tz24Cs',
    appId: '1:781177281533:ios:f898d1c564370328841794',
    messagingSenderId: '781177281533',
    projectId: 'whatsapp-clone-e948a',
    storageBucket: 'whatsapp-clone-e948a.firebasestorage.app',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCecXgY1qLEpcjcuZEzer4E1VPM1tz24Cs',
    appId: '1:781177281533:ios:f898d1c564370328841794',
    messagingSenderId: '781177281533',
    projectId: 'whatsapp-clone-e948a',
    storageBucket: 'whatsapp-clone-e948a.firebasestorage.app',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtq9WMf2kUyz6WKKbhO0KzptcEPumOwIE',
    appId: '1:781177281533:web:adb70f159f519fd2841794',
    messagingSenderId: '781177281533',
    projectId: 'whatsapp-clone-e948a',
    authDomain: 'whatsapp-clone-e948a.firebaseapp.com',
    storageBucket: 'whatsapp-clone-e948a.firebasestorage.app',
    measurementId: 'G-TJKWS87JPZ',
  );
}
